export const Events = {
    VENTA_CREADA: "VENTA_CREADA",
    COMPRA_CREADA: "COMPRA_CREADA",
    PRODUCTO_ACTUALIZADO: "PRODUCTO_ACTUALIZADO",
    AUDITORIA_REGISTRAR: "AUDITORIA_REGISTRAR",
} as const;